name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.12
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run test
      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          subject: Test Failure in ${{ github.repository }}
          body: The test for ${{ github.repository }} failed.
          to: laike9m@gmail.com
          from: GitHub
          server_address: smtp.gmail.com
